import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Adventista",
            artist: "RadioAdventista",
            cover: "https://img.freepik.com/vector-gratis/fondo-notas-ondas-sonido-pentagrama-musical_1017-33911.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://server2.ejeserver.com:8086/live",
            active: true,
        },
        {
            name:"Radio Adventista",
            artist: "RadioAdventista",
            cover: "https://img.freepik.com/vector-gratis/altavoz-musica-fondo-notas-sonido-azul_1017-36709.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://n03.radiojar.com/aesy2chkb?rj-ttl=5&rj-tok=AAABhAW4MCgAedjyJTPgeNauwg",
            active: false,
        },
        {
            name:"Full adventista radio",
            artist: "Fulladventistaradio",
            cover: "https://img.freepik.com/vector-gratis/notas-musicales-fondo-onda-sonido_1017-32863.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://server2.ejeserver.com:8457/stream",
            active: false,
        },
        {
            name:"Radio Adventista",
            artist: "RadioAdventista",
            cover: "https://img.freepik.com/foto-gratis/3d-render-guitarra-acustica-auriculares-musica-ilustracion-3d-designxdxaxdxaxdxa_460848-10586.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://n02.radiojar.com/aesy2chkb?rj-ttl=5&rj-tok=AAABhAXEpaAAIIdeo31vpp9suQ",
            active: false,
        },
        {
            name:"Nuevo Tiempo",
            artist: "NuevoTiempo",
            cover: "https://img.freepik.com/vector-gratis/microfono-auriculares-retro-imagen-realista_1284-14415.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://n04.radiojar.com/kr7r6x2gmg5tv?rj-ttl=5&rj-tok=AAABhAXoj8kAdZ7gmEpG99Pdow",
            active: false,
        },
        {
            name:"radio advent life",
            artist: "radioadventlife",
            cover: "https://img.freepik.com/vector-gratis/icono-vector-realista-conjunto-microfonos-musica-estilo-antiguo-vintage-plata-negro-oro-isla_134830-1392.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://www.adventlife.fr:7777/stream?1666547597676",
            active: false,
        },
        {
            name:"Nuevo Tiempo",
            artist: "NuevoTiempo",
            cover: "https://img.freepik.com/foto-gratis/3d-render-ilustracion-antiguo-receptor-radio-estilo-retro-vintage-aislado-sobre-fondo-purpura_460848-9654.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://n05.radiojar.com/aesy2chkb?rj-ttl=5&rj-tok=AAABhAXpDbkAgxPst9WXVu01PQ",
            active: false,
        },
        {
            name:"Union radio",
            artist: "Unionradio",
            cover: "https://img.freepik.com/vector-gratis/silueta-aparato-radio_23-2147501018.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://unionradio.radioca.st/;",
            active: false,
        },
        {
            name:"Radio joven adventista",
            artist: "radiojovenadventista",
            cover: "https://img.freepik.com/foto-gratis/mujer-escuchando-musica-retrato_53876-98340.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://cloudstream2032.conectarhosting.com:9786/;typemp3",
            active: false,
        },
        {
            name:"Radio joven mundial adventista",
            artist: "radiojovenmundialadventista",
            cover: "https://img.freepik.com/vector-gratis/aire-letrero-neon-marco_23-2148818543.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://server2.ejeserver.com:8457/stream",
            active: false,
        },
        {
            name:"Radio Adventista",
            artist: "RadioAdventista",
            cover: "https://img.freepik.com/vector-gratis/onda-sonido-audio-3d_1217-3196.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://n02.radiojar.com/aesy2chkb?rj-ttl=5&rj-tok=AAABhAY2bNYAg4bPPMN8JPzXjA",
            active: false,
        },
        {
            name:"Secon adventis radio",
            artist: "Seconadventisradio",
            cover: "https://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://s5.radio.co/s6e6f36521/listen",
            active: false, 
        },
        {
            name:"Nou Temps",
            artist: "NouTemps",
            cover: "https://img.freepik.com/foto-gratis/dispositivo-digital-inalambrico-auriculares-rosa_53876-96804.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://n02.radiojar.com/kr7r6x2gmg5tv?rj-ttl=5&rj-tok=AAABhAdECnMAo7nS9CPwe617zg",
            active: false,
        },
        {
            name:"3abn latino",
            artist: "3abnlatino",
            cover: "https://img.freepik.com/vector-gratis/fondo-onda-ecualizador-colorido_52683-33072.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://war.streamguys1.com:7185/Latino",
            active: false,     
        },
    ];
}

export default chillHop;


